.TH "/home/chaperone/Documents/Programs Directory Reference" 3 "Mon Mar 7 2016" "Version 1.0" "Splay tree library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/chaperone/Documents/Programs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLunev\fP"
.br
.in -1c
