.TH "node_t" 3 "Mon Mar 7 2016" "Version 1.0" "Splay tree library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBnode_t\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBnode_t\fP * \fBright\fP"
.br
.ti -1c
.RI "struct \fBnode_t\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBnode_elem\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBnode_key\fP \fBkey\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Splay tree library from the source code\&.
