.TH "splay_tree_t" 3 "Mon Mar 7 2016" "Version 1.0" "Splay tree library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
splay_tree_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnode\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBnode_key\fP(* \fBget_key\fP )(\fBnode_elem\fP elem)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Splay tree library from the source code\&.
